#
## https://rubocop.readthedocs.io/en/latest/cops_security/
#

# https://docs.rubocop.org/rubocop/cops_security.html#securityiomethods
Security/IoMethods:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_security.html#securitycompoundhash
Security/CompoundHash:
  Enabled: true
